# Project Information
site_name: RJZH-wiki

# Repository
repo_name: 'AzurIce/RJZH-wiki'
repo_url: 'https://github.com/AzurIce/RJZH-wiki'

# Contents
nav:
  - 关于:
    - 简介: 'index.md'
    - 如何参与: '简介/如何参与.md'
    - 格式手册: '简介/格式手册.md'
  - 场地申请指南: '场地申请指南.md'

# Theme
theme: 
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - toc.follow
markdown_extensions:
    - toc:
        permalink: 'True'
        slugify: !!python/name:pymdownx.slugs.uslugify